### ISSUE TITLE
Addon Installation error on blender 3.3.1

### ISSUE THREAD

**Issue by optimus007** [takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing#1]
Getting this error while trying to enable the v0.01 of this addon 
![err](https://user-images.githubusercontent.com/6885294/200164587-3f700e5b-9c6d-4678-9801-cdef7a63e580.png)

blender info
![ver](https://user-images.githubusercontent.com/6885294/200164579-25f332b1-ce64-477a-8612-1d9802ecda6b.png)

**Comment by takahirox** [comment]
Thanks for the problem report. Confirmed the problem on my end, too. Investigating...

**Comment by takahirox** [comment]
Figured out the root issue and fixed. Please try again

https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing/releases

**Comment by takahirox** [comment]
Closing because the problem has been resolved on my environment. Please reopen if you still face the problem.
