### ISSUE TITLE
If "As Instance" is checked the instances are not exported

### ISSUE THREAD

**Issue by optimus007** [takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing#4]
![AS INSTANCE](https://user-images.githubusercontent.com/6885294/201723136-2e578aa3-9c2c-41b6-8e79-b575d67153b7.png)

if this checkbox in geometry info is ticked the exporter does not export the instances

there's no bin file and here's the gltf 

```
{
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v3.3.32",
        "version" : "2.0"
    },
    "scene" : 0,
    "scenes" : [
        {
            "name" : "Scene",
            "nodes" : [
                0
            ]
        }
    ],
    "nodes" : [
        {
            "name" : "Plane"
        }
    ]
}
```

is this correct behavior ? or a bug ?

**Comment by takahirox** [comment]
Did you check "Apply Modifier" checkbox in the exporter settings?

https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing#how-to-use

**Comment by optimus007** [comment]
yes , if i keep this checkbox off it exports correctly

**Comment by takahirox** [comment]
Thanks for the response. And I confirmed the problem.

Probably these lines are suspicious...

https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing/blob/5ae881c067310abff2f3dd70f21f1c579d6eeb4c/__init__.py#L51-L52

Let me take a look.

**Comment by takahirox** [comment]
@optimus007

Honestly I'm not so familiar with Blender and Geometry nodes. What is the purpose of checking "As instances" in your example?

**Comment by takahirox** [comment]
Made a PR #5 that can resolve your case. But honestly I'm not sure it is an appropriate way so we may need to investigate more before merging tho.

**Comment by optimus007** [comment]
I'm also not exactly sure about it's use case 
the blender [docs ](https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/input/object_info.html#inputs)for it is not helpful

things i noticed

When its "off"
- if i do `Ctrl+A > Make Instances Real`
It converts all the toruses into separate meshes and these meshes also have the same geometry node modifier which might result in a crash
(eg if i have 100 boxes instances and i do `Make Instances Real` the 100 boxes will become separate meshes and each box will again make its own 100 boxes , so too much boxes  )

When its "on" 
- if i do `Ctrl+A > Make Instances Real`
All the instances become separate meshes(geometry is shared) and they do not have the geometry nodes modifier on them and i can hide the original geometry nodes mesh and export these duplicate meshes as a generic gltf
